# Generated by Django 5.2.9 on 2025-12-31 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProxyConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('proxy_type', models.CharField(choices=[('http', 'Http'), ('https', 'Https'), ('socks4', 'Socks4'), ('socks5', 'Socks5')], default='http', max_length=20)),
                ('host', models.CharField(max_length=255)),
                ('port', models.IntegerField()),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', models.CharField(blank=True, default='', max_length=255)),
                ('is_default', models.BooleanField(default=False)),
                ('enabled', models.BooleanField(default=True)),
                ('bypass_list', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
