# Generated by Django 5.2.9 on 2026-01-02 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiprovider',
            name='provider_type',
            field=models.CharField(choices=[('anthropic', 'Anthropic'), ('deepseek', 'Deepseek'), ('openai', 'Openai'), ('copilot', 'Copilot'), ('custom', 'Custom')], max_length=50),
        ),
    ]
