# Generated by Django 5.2.9 on 2026-01-03 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_app', '0002_alter_aiprovider_provider_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovider',
            name='github_oauth_token',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='aiprovider',
            name='github_username',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='aiprovider',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
