# Generated by Django 5.2.9 on 2025-12-31 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('collections_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('method', models.CharField(max_length=10)),
                ('url', models.TextField()),
                ('resolved_url', models.TextField()),
                ('headers', models.JSONField(default=dict)),
                ('body', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(null=True)),
                ('status_text', models.CharField(blank=True, default='', max_length=100)),
                ('response_headers', models.JSONField(default=dict)),
                ('response_body', models.TextField(blank=True, null=True)),
                ('response_size', models.IntegerField(default=0)),
                ('response_time', models.IntegerField(default=0)),
                ('environment_snapshot', models.JSONField(default=dict)),
                ('proxy_used', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='collections_app.request')),
            ],
            options={
                'verbose_name_plural': 'Request histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
