# Generated by Django 5.2.9 on 2025-12-31 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='environmentvariable',
            name='link_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
