# Generated by Django 5.2.9 on 2026-01-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '__first__'),
        ('environments_app', '0002_environmentvariable_link_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='environments', to='core.workspace'),
        ),
    ]
