# Generated by Django 5.2.9 on 2026-01-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('environments_app', '0004_environment_collection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='environmentvariable',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='environmentvariable',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
