# Generated by Django 5.2.9 on 2025-12-31 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('postman_id', models.CharField(blank=True, max_length=255, null=True)),
                ('schema_version', models.CharField(default='v2.1.0', max_length=50)),
                ('variables', models.JSONField(default=list)),
                ('auth', models.JSONField(blank=True, null=True)),
                ('pre_request_script', models.TextField(blank=True, default='')),
                ('test_script', models.TextField(blank=True, default='')),
                ('sync_id', models.CharField(blank=True, max_length=255, null=True)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('auth', models.JSONField(blank=True, null=True)),
                ('pre_request_script', models.TextField(blank=True, default='')),
                ('test_script', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='collections_app.collection')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='collections_app.folder')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('method', models.CharField(choices=[('GET', 'Get'), ('POST', 'Post'), ('PUT', 'Put'), ('PATCH', 'Patch'), ('DELETE', 'Delete'), ('HEAD', 'Head'), ('OPTIONS', 'Options')], default='GET', max_length=10)),
                ('url', models.TextField()),
                ('headers', models.JSONField(default=list)),
                ('params', models.JSONField(default=list)),
                ('body', models.JSONField(blank=True, null=True)),
                ('auth', models.JSONField(blank=True, null=True)),
                ('pre_request_script', models.TextField(blank=True, default='')),
                ('test_script', models.TextField(blank=True, default='')),
                ('order', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='collections_app.collection')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='collections_app.folder')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
