# Generated by Django 5.2.9 on 2026-01-01 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0001_initial'),
        ('core', '__first__'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='core.workspace'),
        ),
    ]
