# Generated by Django 5.2.9 on 2026-01-02 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0002_collection_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
