# Generated by Django 5.2.9 on 2025-12-31 16:02

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='McpServer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('transport_type', models.CharField(choices=[('stdio', 'Stdio'), ('sse', 'Sse'), ('http', 'Http')], default='stdio', max_length=20)),
                ('command', models.CharField(blank=True, default='', max_length=500)),
                ('args', models.JSONField(default=list)),
                ('url', models.URLField(blank=True, default='')),
                ('headers', models.JSONField(default=dict)),
                ('env_vars', models.JSONField(default=dict)),
                ('is_connected', models.BooleanField(default=False)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='McpServerCapabilities',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tools', models.JSONField(default=list)),
                ('resources', models.JSONField(default=list)),
                ('prompts', models.JSONField(default=list)),
                ('last_refreshed_at', models.DateTimeField(auto_now=True)),
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capabilities', to='mcp_app.mcpserver')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='McpToolExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tool_name', models.CharField(max_length=255)),
                ('arguments', models.JSONField(default=dict)),
                ('result', models.JSONField(null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time', models.IntegerField(default=0)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tool_executions', to='mcp_app.mcpserver')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
