# Generated by Django 5.2.9 on 2026-01-03 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('mcp_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcpserver',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mcp_servers', to='core.workspace'),
        ),
    ]
