# Generated by Django 5.2.9 on 2026-01-29 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='license',
            name='row_signature',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
