# Generated by Django 5.2.9 on 2026-01-29 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licensing_app', '0002_license_row_signature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='trial_started_at',
            field=models.DateTimeField(),
        ),
    ]
