# Generated by Django 5.2.9 on 2025-12-31 16:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncConfiguration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('backend_url', models.URLField()),
                ('api_key', models.CharField(max_length=500)),
                ('user_id', models.CharField(max_length=255)),
                ('enabled', models.BooleanField(default=False)),
                ('auto_sync', models.BooleanField(default=True)),
                ('sync_interval_minutes', models.IntegerField(default=5)),
                ('last_sync_at', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'Sync configuration',
                'verbose_name_plural': 'Sync configurations',
            },
        ),
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.CharField(choices=[('push', 'Push'), ('pull', 'Pull'), ('conflict', 'Conflict')], max_length=20)),
                ('entity_type', models.CharField(max_length=50)),
                ('entity_id', models.UUIDField()),
                ('status', models.CharField(max_length=20)),
                ('details', models.JSONField(default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
